platform :ios, '9.0'
use_frameworks!

target 'demo' do
  
	pod 'Alamofire'
  pod 'AlamofireObjectMapper'
	pod 'SwiftyJSON'
  
#  pod 'SDK-iOS', :path => "../sdk"
  pod 'SDK-iOS', :git =>  "https://github.com/cloudpayments/SDK-iOS", :branch => "fix/d3ds"
  
end
